### ISSUE TITLE
Support all statements that use OP_JCMP

### ISSUE THREAD

**Issue by Psimage** [darknesswind/NutCracker#13]
OP_JCMP was added in 3.x as an optimization for single comparison expressions instead of using OP_CMP and conditional jump (OP_JZ is the only one in 3.x?).
Currently those statements are not recognized correctly when OP_JCMP is used:
1.  If/IfElse
![image](https://user-images.githubusercontent.com/787038/31294457-9bfc8592-aae3-11e7-8971-1967ce4503b3.png)
2. While/DoWhile
![image](https://user-images.githubusercontent.com/787038/31294590-204d61ae-aae4-11e7-85e1-512ae188fb31.png)

**Comment by darknesswind** [comment]
![image](https://user-images.githubusercontent.com/3053816/31307278-5694441c-ab93-11e7-9619-d77013ec69f5.png)

It seens that do-while loop is not complete yet in the origin version of code
