### ISSUE TITLE
Crash when generating DoWhileStatement

### ISSUE THREAD

**Issue by Psimage** [darknesswind/NutCracker#15]
In some cases `void NutFunction::DecompileDoWhileLoop( VMState& state, int endPos) const` `endPos > state.IP()` which causes `ExpressionPtr condition;` to be null and crash later when printing DoWhileStatement.

Tested on: [script.zip](https://github.com/darknesswind/NutCracker/files/1370548/script.zip)

**Comment by Psimage** [comment]
Can this be due to OP_LINE between OP_JZ and OP_JMP?

**Comment by darknesswind** [comment]
It seens that there are three do-while statement in on function, and they jump back to thie same pos, and the current code only consider the outer loop.

**Comment by darknesswind** [comment]
there is a 'break' operation in the inner loop using OP_JCMP, it cause the crash

**Comment by Psimage** [comment]
Yeah. Broke it with this
![image](https://user-images.githubusercontent.com/787038/31379450-f83b4b2e-adb6-11e7-8dd5-95739bd30b1c.png)

**Comment by darknesswind** [comment]
> Can this be due to OP_LINE between OP_JZ/OP_JCMP and OP_JMP?
emmmm... , maybe this will happen in some condition?

**Comment by darknesswind** [comment]
I think the pattern of this function will looks like
`for (int i = 0; i < 10; ++i)`
`{`
`    if (...) continue;`
`    if (...) continue;`
`    if (...) continue;`
`    if (...) continue;`
`}`
