### ISSUE TITLE
你好，请问能针对当前战场兄弟的文件做个解析吗？

### ISSUE THREAD

**Issue by gisphm** [darknesswind/NutCracker#17]
新的DLC野兽和探索出了，我们目前在做战场兄弟新版本的汉化，但是没法用现在的项目代码解开加密的cnut文件，我们也缺少能做C++编码工作的人。

请问大佬能帮个忙吗？

**Comment by darknesswind** [comment]
木有时间啊，况且我对逆向工程并不在行。更新新版本应该不至于会改到脚本语言的加密方式吧，那你们旧版本是怎么破的……

**Comment by darknesswind** [comment]
当然，如果你们已经知道加密算法，只是缺人改改代码的话我倒是可以改一下

**Comment by gisphm** [comment]
我们找不到旧版本破解的人了（或者说之前的汉化小组（某侠）的人不愿意分享）。
我们目前没找到擅长搞通这游戏的加密算法的人。
不过，还是谢谢你了，这个项目至少给了点盼头，毕竟目前汉化是看着UI做的，龟速进行中。
