### ISSUE TITLE
For loop expression is not supported?

### ISSUE THREAD

**Issue by Psimage** [darknesswind/NutCracker#7]
![image 1](https://user-images.githubusercontent.com/787038/30971054-946f419a-a46f-11e7-8a58-a969e7465139.png)

**Comment by darknesswind** [comment]
OP_JCMP added in squirrel 3, so the origin code(for squirrel 2) not support this

**Comment by darknesswind** [comment]
![image](https://user-images.githubusercontent.com/3053816/30975962-1d852a86-a4a6-11e7-88af-0122780c3df2.png)
arg2: lhs
arg0: rhs
arg3: compare operator
arg1: ip offset
