### ISSUE TITLE
In some cases foreach loop decompilation is invalid

### ISSUE THREAD

**Issue by Psimage** [darknesswind/NutCracker#8]
![image](https://user-images.githubusercontent.com/787038/30984618-782cab36-a496-11e7-9637-0778fb5984d1.png)

**Comment by Psimage** [comment]
Shouldn't 'b' be only visible in foreach scope?

**Comment by darknesswind** [comment]
yes, but I don't have enough time work on this feature

**Comment by Psimage** [comment]
![image](https://user-images.githubusercontent.com/787038/31024670-7f0d941c-a548-11e7-86c6-30881a6bccdb.png)
https://github.com/darknesswind/NutCracker/blob/45cadc1d3ac3c012b628a80ca16c1533c9794f5a/nutcracker/NutScript.cpp#L147-L165

In the BAD version there is no @ITERATOR@ special local variable generated

**Comment by Psimage** [comment]
Same result with v3.0.7

**Comment by Psimage** [comment]
I fixed this. Will push soon.
